"""Added content property to Post class

Revision ID: 368a98aea4ce
Revises: 7040474b1d41
Create Date: 2023-09-28 14:06:36.979154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368a98aea4ce'
down_revision = '7040474b1d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
