"""Added balance property to User class

Revision ID: 51c714309cb9
Revises: e57018584051
Create Date: 2023-09-28 15:14:17.401426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c714309cb9'
down_revision = 'e57018584051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('balance')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
