"""empty message

Revision ID: 7040474b1d41
Revises: c62987911e61
Create Date: 2023-09-27 12:15:48.595308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7040474b1d41'
down_revision = 'c62987911e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_posts_title', type_='unique')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stocks_company_name', type_='unique')
        batch_op.drop_constraint('uq_stocks_symbol', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stocks_symbol', ['symbol'])
        batch_op.create_unique_constraint('uq_stocks_company_name', ['company_name'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_posts_title', ['title'])

    # ### end Alembic commands ###
