"""Fixing trade table

Revision ID: 7230e90aeec9
Revises: ac1c7caa2240
Create Date: 2023-10-02 03:40:31.052570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7230e90aeec9'
down_revision = 'ac1c7caa2240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trades_stock_current_value_stocks', type_='foreignkey')
        batch_op.drop_constraint('fk_trades_user_balance_users', type_='foreignkey')
        batch_op.drop_column('stock_current_value')
        batch_op.drop_column('user_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_balance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('stock_current_value', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key('fk_trades_user_balance_users', 'users', ['user_balance'], ['balance'])
        batch_op.create_foreign_key('fk_trades_stock_current_value_stocks', 'stocks', ['stock_current_value'], ['current_value'])

    # ### end Alembic commands ###
