"""Added user_id and stock_id to Trade class

Revision ID: c62987911e61
Revises: dee09239540d
Create Date: 2023-09-27 11:19:58.847434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62987911e61'
down_revision = 'dee09239540d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trades_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_trades_stock_id_stocks'), 'stocks', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trades_stock_id_stocks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trades_user_id_users'), type_='foreignkey')
        batch_op.drop_column('stock_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
