"""Added unique attribute

Revision ID: dee09239540d
Revises: 0bbbcf1b0d8d
Create Date: 2023-09-26 14:59:00.018974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee09239540d'
down_revision = '0bbbcf1b0d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_posts_title'), ['title'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_stocks_company_name'), ['company_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_stocks_symbol'), ['symbol'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stocks_symbol'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_stocks_company_name'), type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_title'), type_='unique')

    # ### end Alembic commands ###
